spring:
  application:
    name: restaurant

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

  output:
    ansi: ${SPRING_OUTPUT_ANSI_ENABLED}

  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED}